name: ci

on:
  push:
    branches:
      - "master"

jobs:
  pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install -r requirements.txt

    - name: Install CLI tools from GitHub
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        source: "github"
        # Using GitHub token from the github context
        github_pat: ${{ github.token }}
        s2i: "1.2"
    - name: Ejecutar s2i
      run: s2i build https://github.com/mjbernal/prueba-gha.git --context-dir=mymodel seldonio/seldon-core-s2i-python3 mjbernal/mymodel

    - uses: docker-practice/actions-setup-docker@master
    - run:
        docker images

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Push
      run: docker push mjbernal/mymodel:latest